theme: minima
title: "Strong opinions about things that don't matter"
author: "Juklifa"
description: "Welcome to my personal portfolio. Here you can find my travel blog, book reviews, articles I want to read, and my to-do list."
